###User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "2Test name",
  "email": "2test@test.com",
  "password": "password",
  "password_confirmation": "password"
}